#!/bin/bash

# Author   : Gcaufy
# Date     : 2020/03/01

set -e

VERSION="1.0.5"
SHELLS="bash zsh fish"
PREFIX="${HOME}/.sshman"

for s in $SHELLS; do
  if ! command -v "$s" > /dev/null; then
    SHELLS=${SHELLS/$s/}
  fi
done

if [[ ${#SHELLS} -lt 3 ]]; then
  echo "No shell configuration to be updated."
  exit 0
fi

function git_install() {
  if [[ -d "${PREFIX}" ]]; then
    cd "${PREFIX}"
    git pull
  else
    git clone https://github.com/Gcaufy/sshman.git "${PREFIX}"
    cd "${PREFIX}"
  fi
  git checkout v${VERSION}
}

function tar_install() {
  local _url
  _url="https://github.com/Gcaufy/sshman/archive/v${VERSION}.tar.gz"
  echo -n "Downloading package from: $_url"
  mkdir -p "${PREFIX}"
  curl -sSL $_url | tar xz - --strip-components=1 -C "${PREFIX}"
}

function append_line() {
  set -e

  local update line file pat lno
  update="$1"
  line="$2"
  file="$3"
  pat="${4:-}"
  lno=""

  echo "Update $file:"
  echo "  - $line"
  if [ -f "$file" ]; then
    if [ $# -lt 4 ]; then
      lno=$(\grep -nF "$line" "$file" | sed 's/:.*//' | tr '\n' ' ')
    else
      lno=$(\grep -nF "$pat" "$file" | sed 's/:.*//' | tr '\n' ' ')
    fi
  fi
  if [ -n "$lno" ]; then
    echo "    - Already exists: line #$lno"
  else
    if [ "$update" -eq 1 ]; then
      [ -f "$file" ] && echo >> "$file"
      echo "$line" >> "$file"
      echo "    + Added"
    else
      echo "    ~ Skipped"
    fi
  fi
  echo
  set +e
}

function install() {
  if ! command -v "git" > /dev/null; then
    tar_install
  else
    git_install
  fi
  echo -n "Update alias"
  update_alias

  echo -e "Install successfully. current version is: v$(cat $PREFIX/version.txt) \n"
  echo -e 'Finished. Restart your shell or reload config file.'
  [[ "$SHELLS" =~ bash ]] && echo -e '   source ~/.bashrc  # bash'
  [[ "$SHELLS" =~ zsh ]]  && echo -e "   source ${ZDOTDIR:-~}/.zshrc   # zsh"
  echo
  echo
}

function update_alias() {
  for shell in $SHELLS; do
    [[ "$shell" = fish ]] && continue
    [ "$shell" = zsh ] && dest=${ZDOTDIR:-~}/.zshrc || dest=~/.bashrc
    append_line 1 "alias s=\"'${PREFIX}/sshman'\"" "${dest}"
    source "${dest}"
  done
}

install
