name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run: |
        [[ "$(uname)" == "Darwin" ]] && echo "bats installed in macos by default" || echo "Not MacOS"
        [[ "$(uname)" == "Linux" ]] && sudo apt-get install bats || echo "Not Linux"
    - name: Run test
      run: make test
