name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run: |
        git clone https://github.com/sstephenson/bats.git ~/.bats
        cd ~/.bats
        ./install.sh /usr/local
    - name: Run test
      run: make test
